notifications:
  email: false

rvm:
  - 2.5.3 # deployed

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - ROBOT_ENVIRONMENT=local

language: ruby

before_install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install imagemagick libimage-exiftool-perl
  - gem update --system
  - gem install bundler
