notifications:
  email: false

rvm:
  - 2.2.4 # deployed
  - 2.3.1
  - 2.3.4

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - ROBOT_ENVIRONMENT=local

language: ruby

before_install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install imagemagick libimage-exiftool-perl 
