jp2-create:
    prerequisite: start-assembly
    batch_limit:  1000
    error_limit:  10

checksum-compute:
    prerequisite: jp2-create
    batch_limit:  1000
    error_limit:  10

checksum-compare:
    prerequisite: checksum-compute
    batch_limit:  1000
    error_limit:  10

exif-collect:
    prerequisite: checksum-compare
    batch_limit:  1000
    error_limit:  10

accessioning-initiate:
    prerequisite: exif-collect
    batch_limit:  1000
    error_limit:  10

repository: dor
