jp2-create:
    prerequisite: start-assembly
    batch_limit:  1000
    error_limit:  10

checksum-compute:
    prerequisite:
      - start-assembly
      - jp2-create
    batch_limit:  1000
    error_limit:  10

checksum-compare:
    prerequisite:
      - start-assembly
      - jp2-create      
      - checksum-compute
    batch_limit:  1000
    error_limit:  10

exif-collect:
    prerequisite:
      - start-assembly
      - jp2-create      
      - checksum-compute      
      - checksum-compare
    batch_limit:  1000
    error_limit:  10

accessioning-initiate:
    prerequisite:
      - start-assembly
      - jp2-create      
      - checksum-compute      
      - checksum-compare      
      - exif-collect
    batch_limit:  1000
    error_limit:  10

repository: dor
