jp2-create:
    prerequisite: start-assembly
    batch_limit:  1000
    error_limit:  10

checksum:
    prerequisite: jp2-create
    batch_limit:  1000
    error_limit:  10

checksum-compare:
    prerequisite: checksum
    batch_limit:  1000
    error_limit:  10

repository: dor
